# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo_module.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1398, 842)
        font = QtGui.QFont()
        font.setPointSize(15)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 211, 330))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 209, 328))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox = QtWidgets.QToolBox(self.scrollAreaWidgetContents)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBox.setObjectName("toolBox")
        self.rCWGAN = QtWidgets.QWidget()
        self.rCWGAN.setGeometry(QtCore.QRect(0, 0, 193, 192))
        self.rCWGAN.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.rCWGAN.setObjectName("rCWGAN")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.rCWGAN)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.rCWGAN)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_3.addWidget(self.textBrowser)
        self.toolBox.addItem(self.rCWGAN, "")
        self.WGAN_GP = QtWidgets.QWidget()
        self.WGAN_GP.setGeometry(QtCore.QRect(0, 0, 98, 87))
        self.WGAN_GP.setObjectName("WGAN_GP")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.WGAN_GP)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.WGAN_GP)
        self.textBrowser_2.setStyleSheet("")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.horizontalLayout_4.addWidget(self.textBrowser_2)
        self.toolBox.addItem(self.WGAN_GP, "")
        self.infoWGAN = QtWidgets.QWidget()
        self.infoWGAN.setGeometry(QtCore.QRect(0, 0, 98, 87))
        self.infoWGAN.setObjectName("infoWGAN")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.infoWGAN)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.infoWGAN)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.horizontalLayout_5.addWidget(self.textBrowser_3)
        self.toolBox.addItem(self.infoWGAN, "")
        self.horizontalLayout.addWidget(self.toolBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(220, 10, 1171, 621))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.model_config = QtWidgets.QWidget()
        self.model_config.setObjectName("model_config")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.model_config)
        self.verticalLayout.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget.addTab(self.model_config, "")
        self.model_output = QtWidgets.QWidget()
        self.model_output.setObjectName("model_output")
        self.tabWidget.addTab(self.model_output, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1398, 26))
        self.menuBar.setObjectName("menuBar")
        self.menubar = QtWidgets.QMenu(self.menuBar)
        self.menubar.setObjectName("menubar")
        self.menubar_2 = QtWidgets.QMenu(self.menuBar)
        self.menubar_2.setObjectName("menubar_2")
        MainWindow.setMenuBar(self.menuBar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dockWidget.setFont(font)
        self.dockWidget.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.textEdit = QtWidgets.QTextEdit(self.dockWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("")
        self.textEdit.setReadOnly(True)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_8.addWidget(self.textEdit)
        self.dockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menuBar.addAction(self.menubar.menuAction())
        self.menuBar.addAction(self.menubar_2.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "深度学习工具箱"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">WGAN-GP + CGAN + 回归器(多层感知机)</p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.rCWGAN), _translate("MainWindow", "rCWGAN"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.WGAN_GP), _translate("MainWindow", "WGAN-GP"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.infoWGAN), _translate("MainWindow", "infoWGAN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.model_config), _translate("MainWindow", "模型配置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.model_output), _translate("MainWindow", "模型输出"))
        self.menubar.setTitle(_translate("MainWindow", "终端"))
        self.menubar_2.setTitle(_translate("MainWindow", "帮助"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "终端"))
        self.action.setText(_translate("MainWindow", "显示"))
        self.action_3.setText(_translate("MainWindow", "清空内容"))

