# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Model_Structure.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Structure(object):
    def setupUi(self, Structure):
        Structure.setObjectName("Structure")
        Structure.resize(1034, 549)
        self.verticalLayout = QtWidgets.QVBoxLayout(Structure)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(Structure)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bn_plus = QtWidgets.QPushButton(Structure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_plus.sizePolicy().hasHeightForWidth())
        self.bn_plus.setSizePolicy(sizePolicy)
        self.bn_plus.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bn_plus.setText("")
        self.bn_plus.setObjectName("bn_plus")
        self.horizontalLayout_2.addWidget(self.bn_plus)
        self.bn_minus = QtWidgets.QPushButton(Structure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_minus.sizePolicy().hasHeightForWidth())
        self.bn_minus.setSizePolicy(sizePolicy)
        self.bn_minus.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bn_minus.setText("")
        self.bn_minus.setObjectName("bn_minus")
        self.horizontalLayout_2.addWidget(self.bn_minus)
        spacerItem = QtWidgets.QSpacerItem(225, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.bn_go_up = QtWidgets.QPushButton(Structure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_go_up.sizePolicy().hasHeightForWidth())
        self.bn_go_up.setSizePolicy(sizePolicy)
        self.bn_go_up.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bn_go_up.setText("")
        self.bn_go_up.setObjectName("bn_go_up")
        self.horizontalLayout_2.addWidget(self.bn_go_up)
        self.bn_go_down = QtWidgets.QPushButton(Structure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn_go_down.sizePolicy().hasHeightForWidth())
        self.bn_go_down.setSizePolicy(sizePolicy)
        self.bn_go_down.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bn_go_down.setText("")
        self.bn_go_down.setObjectName("bn_go_down")
        self.horizontalLayout_2.addWidget(self.bn_go_down)
        self.bn_saveStruct = QtWidgets.QPushButton(Structure)
        self.bn_saveStruct.setObjectName("bn_saveStruct")
        self.horizontalLayout_2.addWidget(self.bn_saveStruct)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Structure)
        QtCore.QMetaObject.connectSlotsByName(Structure)

    def retranslateUi(self, Structure):
        _translate = QtCore.QCoreApplication.translate
        Structure.setWindowTitle(_translate("Structure", "Form"))
        self.treeWidget.headerItem().setText(0, _translate("Structure", "网络"))
        self.treeWidget.headerItem().setText(1, _translate("Structure", "参数"))
        self.treeWidget.headerItem().setText(2, _translate("Structure", "其他"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Structure", "回归器"))
        self.treeWidget.topLevelItem(0).setText(1, _translate("Structure", "---"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.bn_saveStruct.setText(_translate("Structure", "保存模型"))

